apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
nameSuffix: -01
resources:
- ../../bases/app
- namespace.yml
patchesStrategicMerge:
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: realtime
  spec:
    template:
      spec:
        containers:
          - name: realtime
            resources:
              requests:
                cpu: 150m
                memory: 150Mi
replicas:
- count: 3
  name: realtime
images:
- name: manojkumarkudla/gitops
  newTag: hellov1.1
