apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
nameSuffix: -01
resources:
- ../../bases/app
- namespace.yml
patchesStrategicMerge:
images:
- name: manojkumarkudla/gitops
  newTag: hellov1.1
