apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realtime-prd
nameSuffix: -prd
resources:
- ../../bases/app
- namespace.yml
patchesStrategicMerge:
images:
- name: manojkumarkudla/gitops
  newTag: hellov1.2
