apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
nameSuffix: -01
resources:
- ../../bases/app
- namespace.yml
transformers:
- labels.yml
patchesStrategicMerge:
images:
- name: manojkumarkudla/gitops
  newTag: nginx1.1
